name: "Integration Test"

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    name: Python 3.8 | TiDB nightly | Ubuntu latest
    runs-on: ubuntu-latest

    services:
      tidb_nightly:
        image: pingcap/tidb:nightly
        ports:
          - 4000:4000
      tidb_5.1:
        image: pingcap/tidb:v5.1.0
        ports:
          - 4001:4000
      tidb_4.0:
        image: pingcap/tidb:v4.0.0
        ports:
          - 4002:4000

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        pip install -r requirements_dev.txt
        pip install .

    - name: Run tests tidb_nightly
      run: |
        pytest test/functional/adapter/utils/test_util.py
        pytest test/functional/adapter/basic/test_tidb.py

    - name: Run tests tidb_v5.0.1 up
      run: |
        pytest test/functional/adapter/utils/test_util.py
        pytest test/functional/adapter/basic/test_tidb_v5_1_v5_2.py

    - name: Run tests tidb_v4.0.0 up
      run: |
        pytest test/functional/adapter/utils/test_util.py
        pytest test/functional/adapter/basic/test_tidb_v4_0_v5_0.py
        
